name: SSH into EC2 Behind VPN

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install OpenVPN
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y openvpn

      - name: Set Up VPN Configuration and Credentials
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn
          # echo "${{ secrets.VPN_USERNAME }}" > vpn_username.txt
          # echo "${{ secrets.VPN_PASSWORD }}" > vpn_password.txt
          echo "${{ secrets.VPN_USERNAME }}" > vpn_credentials.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> vpn_credentials.txt
      - name: Cache OpenVPN
        id: cache-openvpn
        uses: actions/cache@v2
        with:
          path: ~/openvpn
          key: ${{ runner.os }}-openvpn-${{ hashFiles('**/workflow.yml') }}

      - name: Verify OpenVPN Installation
        run: |
          if [ -f ~/openvpn/openvpn ]; then
            echo "OpenVPN found in cache"
            ~/openvpn/openvpn --version
          else
            echo "OpenVPN not found in cache, installing..."
            sudo apt-get update
            sudo apt-get install -y openvpn
            mkdir -p ~/openvpn
            sudo cp $(which openvpn) ~/openvpn/
            sudo chown $USER:$USER ~/openvpn/openvpn
          fi
          echo "OpenVPN path: $(which openvpn)"
          echo "Content of ~/openvpn:"
          ls -l ~/openvpn

      - name: Set Up VPN Configuration and Credentials
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn
          echo "${{ secrets.VPN_USERNAME }}" > vpn_credentials.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> vpn_credentials.txt
          echo "VPN config and credentials set up"

      - name: Connect to VPN
        run: |
          echo "Starting OpenVPN..."
          sudo ~/openvpn/openvpn --config vpn_config.ovpn --auth-user-pass vpn_credentials.txt --daemon
          echo "Waiting for connection..."
          sleep 10
          if ip addr show tun0 > /dev/null 2>&1; then
            echo "VPN connection established"
            ip addr show tun0
          else
            echo "VPN connection failed"
            sudo cat /var/log/syslog | grep openvpn
            exit 1
          fi
      # - name: Connect to VPN
      #   run: |
      #     cat vpn_credentials.txt
      #     sudo openvpn --config vpn_config.ovpn --auth-user-pass vpn_credentials.txt --daemon
      #     sleep 10
      #     sudo cat /var/log/syslog | grep openvpn

      # - name: OpenVPN-Connect
      #   uses: kota65535/github-openvpn-connect-action@v3.0.0
      #   with:
      #      config_file: vpn_config.ovpn
      #      username: ${{ secrets.VPN_USERNAME }}
      #      password: ${{ secrets.VPN_PASSWORD }}
      #      # tls_auth_key: # optional
      #      # tls_crypt_key: # optional
      #      # tls_crypt_v2_key: # optional
      #      # client_key: # optional

      - name: SSH into EC2 and Create Folder
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: mkdir -p ~/new_folder

      - name: Clean Up VPN Configuration
        run: |
          rm -f vpn_config.ovpn vpn_credentials.txt
